config/routes.rb
Tasklist::Application.routes.draw do

  resources :tasks

  root 'tasks#index'

end

app/models/task.rb
class Task < ActiveRecord::Base
	validates :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def index
		@tasks = Task.all
	end

	def new
		@task = Task.new
	end

	def create
		@task = Task.new(task_params)

		if @task.save
			redirect_to tasks_path
		else
			render action: 'new'
		end
	end

	def destroy
		@task = Task.find(params[:id])
		@task.destroy

		redirect_to tasks_path
	end


	private

		def task_params
      params.require(:task).permit(:content)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.haml
%html
  %head
    %title Tasklist
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    %div{"data-role" => "page", "data-url" => request.path}
      %br
        = yield

app/views/tasks/_form.haml
%div{"data-role" => "content"}
  = form_for(@task) do |f|
    - if @task.errors.any?
      #error_explanation
        %h2
          = pluralize(@task.errors.count, "error")
          prohibited this task from being saved:
        %ul
          - @task.errors.full_messages.each do |msg|
            %li= msg
    .field
      = f.label :content
      %br
        = f.text_field :content
    .actions
      = f.submit

app/views/tasks/index.haml
%div{"data-role" => "header"}
  %h1
    My Tasks
%div{"data-role" => "content"}
  %ol{"data-role" => "listview"}
    - @tasks.each do |task|
      %li
        %h2= task.content
      = link_to "Complete", task, method: "delete", "data-role" => "button", "data-inline" => "true"
%br
%br
%div{"data-role" => "footer", "data-role" => "button"}
  = link_to 'New Task', new_task_path, "data-role" => "button"

app/views/tasks/new.haml
%div{"data-role" => "header"}
  %h1 New Task
= render 'form'
%div{"data-role" => "footer"}
  = link_to 'Back', tasks_path